import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { ExportDialog, type ExportOptions } from '@/components/ExportDialog';
import { saveSkill, validateExportPath, type ExportResult } from '@/lib/export';
import { FileDown, CheckCircle2, AlertCircle, Loader2, FolderOpen } from 'lucide-react';
import { open as openPath } from '@tauri-apps/plugin-shell';

/**
 * Skill Save Test Component
 * 
 * Tests the complete skill save functionality including:
 * - Creating skill folder structure
 * - Saving SKILL.md file
 * - Copying reference screenshots
 * - Copying assets
 * - Path validation
 * - Error handling
 * 
 * Requirements: FR-6.4 (Save Implementation)
 */
export function SkillSaveTest() {
  const [isOpen, setIsOpen] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [exportResult, setExportResult] = useState<ExportResult | null>(null);
  const [exportError, setExportError] = useState<string | null>(null);

  // Sample SKILL.md content
  const sampleSkillContent = `---
name: create-user-account
description: Create a new user account in the admin dashboard with proper validation
compatibility: Web application, requires admin access
license: Apache-2.0
metadata:
  author: Skill-E
  version: "1.0"
  recorded: "${new Date().toISOString().split('T')[0]}"
  source: demonstration
---

# Create User Account

This skill demonstrates how to create a new user account in the admin dashboard.

## Parameters

| Parameter | Type | Required | Description |
|-----------|------|----------|-------------|
| \`{username}\` | text | yes | Username for the new account |
| \`{email}\` | email | yes | Email address for the account |
| \`{role}\` | selection | yes | User role: \`admin\` \\| \`user\` \\| \`viewer\` |

## When to Use

- When you need to create a new user account
- When onboarding a new team member
- When setting up test accounts

## Prerequisites

- Admin access to the dashboard
- Valid email address
- Appropriate permissions to create users

## Instructions

### Step 1: Navigate to Users Page

1. Click on "Users" in the left sidebar
2. Wait for the users list to load

> **Note**: Make sure you're logged in as an admin

### Step 2: Open Create User Form

1. Click the "Create User" button in the top-right corner
2. The create user form should appear

### Step 3: Fill in User Details

1. Enter the username in the "Username" field: \`{username}\`
2. Enter the email in the "Email" field: \`{email}\`
3. Select the role from the dropdown: \`{role}\`

**If \`{role}\` = \`admin\`:**
1. Check the "Grant admin privileges" checkbox
2. Confirm the admin access warning

**If \`{role}\` = \`user\` or \`viewer\`:**
1. Leave admin privileges unchecked
2. Continue to next step

### Step 4: Submit Form

1. Click the "Create User" button at the bottom
2. Wait for the success message

### Step 5: Verification

1. Check that the success message appears
2. Verify the new user appears in the users list
3. Confirm the user has the correct role badge

## Verification

- [ ] User appears in the users list
- [ ] User has correct username and email
- [ ] User has correct role assigned
- [ ] Success notification was shown

## Troubleshooting

| Problem | Solution |
|---------|----------|
| "Username already exists" | Choose a different username |
| "Invalid email format" | Check email format is correct |
| Form doesn't submit | Check all required fields are filled |
| Permission denied | Verify you have admin access |

---
*Generated by Skill-E from demonstration recording*
`;

  // Sample screenshot paths (these would come from the session)
  const sampleScreenshots = [
    '/tmp/skill-e-sessions/test-session/frame_001.webp',
    '/tmp/skill-e-sessions/test-session/frame_002.webp',
    '/tmp/skill-e-sessions/test-session/frame_003.webp',
  ];

  const handleExport = async (options: ExportOptions) => {
    console.log('Export requested with options:', options);
    setIsExporting(true);
    setExportError(null);
    setExportResult(null);

    try {
      // Validate path first
      const isValid = await validateExportPath(options.exportPath, options.skillName);
      
      if (!isValid) {
        throw new Error(`Skill "${options.skillName}" already exists in this location. Please choose a different name or delete the existing folder.`);
      }

      // Save the skill
      const result = await saveSkill(
        options,
        sampleSkillContent,
        options.includeScreenshots ? sampleScreenshots : undefined,
        options.includeAssets ? [] : undefined // No assets in this test
      );

      console.log('Export successful:', result);
      setExportResult(result);
      setIsOpen(false);
    } catch (error) {
      console.error('Export failed:', error);
      setExportError(error instanceof Error ? error.message : String(error));
    } finally {
      setIsExporting(false);
    }
  };

  const handleOpenFolder = async (path: string) => {
    try {
      await openPath(path);
    } catch (error) {
      console.error('Failed to open folder:', error);
    }
  };

  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header */}
        <div className="space-y-2">
          <h1 className="text-3xl font-bold">Skill Save Test</h1>
          <p className="text-muted-foreground">
            Test the complete skill save implementation (Task 6)
          </p>
        </div>

        {/* Test Controls */}
        <div className="space-y-4 p-6 border rounded-lg bg-card">
          <h2 className="text-xl font-semibold">Test Controls</h2>
          
          <div className="space-y-3">
            <Button
              onClick={() => setIsOpen(true)}
              className="w-full"
              size="lg"
              disabled={isExporting}
            >
              {isExporting ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Exporting...
                </>
              ) : (
                <>
                  <FileDown className="h-4 w-4 mr-2" />
                  Test Skill Export
                </>
              )}
            </Button>

            <div className="p-3 rounded-md bg-muted/50 text-xs space-y-1">
              <p className="font-semibold">This test will:</p>
              <ul className="ml-4 list-disc space-y-1 text-muted-foreground">
                <li>Create a skill folder with the name you choose</li>
                <li>Save a sample SKILL.md file inside</li>
                <li>Copy reference screenshots if selected (simulated)</li>
                <li>Validate the export was successful</li>
              </ul>
            </div>
          </div>
        </div>

        {/* Success Message */}
        {exportResult && (
          <div className="p-4 border border-green-500 bg-green-500/10 rounded-lg space-y-3 animate-in fade-in slide-in-from-top-2">
            <div className="flex items-center gap-3">
              <CheckCircle2 className="h-5 w-5 text-green-500" />
              <div>
                <p className="font-medium text-green-500">Export Successful!</p>
                <p className="text-sm text-muted-foreground">
                  Skill saved to: {exportResult.skillFolderPath}
                </p>
              </div>
            </div>

            <div className="space-y-2 text-sm">
              <div className="grid grid-cols-[180px_1fr] gap-2">
                <span className="text-muted-foreground">Skill Folder:</span>
                <span className="font-mono text-xs break-all">{exportResult.skillFolderPath}</span>
              </div>
              <div className="grid grid-cols-[180px_1fr] gap-2">
                <span className="text-muted-foreground">SKILL.md Path:</span>
                <span className="font-mono text-xs break-all">{exportResult.skillFilePath}</span>
              </div>
              <div className="grid grid-cols-[180px_1fr] gap-2">
                <span className="text-muted-foreground">Screenshots Copied:</span>
                <span className="font-medium">{exportResult.screenshotsCopied}</span>
              </div>
              <div className="grid grid-cols-[180px_1fr] gap-2">
                <span className="text-muted-foreground">Assets Copied:</span>
                <span className="font-medium">{exportResult.assetsCopied}</span>
              </div>
            </div>

            <Button
              onClick={() => handleOpenFolder(exportResult.skillFolderPath)}
              variant="outline"
              size="sm"
              className="w-full"
            >
              <FolderOpen className="h-4 w-4 mr-2" />
              Open Skill Folder
            </Button>
          </div>
        )}

        {/* Error Message */}
        {exportError && (
          <div className="p-4 border border-destructive bg-destructive/10 rounded-lg flex items-start gap-3 animate-in fade-in slide-in-from-top-2">
            <AlertCircle className="h-5 w-5 text-destructive mt-0.5" />
            <div className="flex-1">
              <p className="font-medium text-destructive">Export Failed</p>
              <p className="text-sm text-muted-foreground mt-1">{exportError}</p>
            </div>
            <Button
              onClick={() => setExportError(null)}
              variant="ghost"
              size="sm"
            >
              Dismiss
            </Button>
          </div>
        )}

        {/* Sample Content Preview */}
        <div className="space-y-4 p-6 border rounded-lg bg-card">
          <h2 className="text-xl font-semibold">Sample SKILL.md Content</h2>
          
          <div className="p-4 rounded-md bg-muted/50 font-mono text-xs overflow-auto max-h-96">
            <pre className="whitespace-pre-wrap">{sampleSkillContent}</pre>
          </div>

          <p className="text-sm text-muted-foreground">
            This is the content that will be saved to SKILL.md when you export.
          </p>
        </div>

        {/* Test Cases */}
        <div className="space-y-4 p-6 border rounded-lg bg-card">
          <h2 className="text-xl font-semibold">Test Cases</h2>
          
          <div className="space-y-3 text-sm">
            <div className="space-y-2">
              <h3 className="font-semibold">✓ Test Cases to Verify:</h3>
              <ul className="space-y-1 ml-4 list-disc text-muted-foreground">
                <li>Skill folder is created at the specified path</li>
                <li>SKILL.md file is saved with correct content</li>
                <li>references/ folder is created when screenshots are included</li>
                <li>Screenshots are copied and renamed (step1.png, step2.png, etc.)</li>
                <li>assets/ folder is created when assets are included</li>
                <li>Export fails gracefully if folder already exists</li>
                <li>Export fails gracefully if path is not writable</li>
                <li>File validation checks file exists and has content</li>
                <li>Success result includes all paths and counts</li>
                <li>"Open Folder" button opens the skill folder in file explorer</li>
              </ul>
            </div>

            <div className="space-y-2 pt-4 border-t">
              <h3 className="font-semibold">🧪 Manual Verification Steps:</h3>
              <ol className="space-y-1 ml-4 list-decimal text-muted-foreground">
                <li>Click "Test Skill Export" button</li>
                <li>Choose a skill name (e.g., "test-skill")</li>
                <li>Select an export location (or use default)</li>
                <li>Enable "Include Screenshots" option</li>
                <li>Click "Export" button</li>
                <li>Wait for success message</li>
                <li>Click "Open Skill Folder" button</li>
                <li>Verify folder structure matches expected layout</li>
                <li>Open SKILL.md and verify content is correct</li>
                <li>Check references/ folder for screenshots (if included)</li>
              </ol>
            </div>
          </div>
        </div>

        {/* Requirements Coverage */}
        <div className="space-y-4 p-6 border rounded-lg bg-card">
          <h2 className="text-xl font-semibold">Requirements Coverage</h2>
          
          <div className="space-y-2 text-sm">
            <div className="flex items-start gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500 mt-0.5" />
              <div>
                <span className="font-medium">FR-6.4:</span>
                <span className="text-muted-foreground ml-2">
                  Create skill folder (skill-name/)
                </span>
              </div>
            </div>
            
            <div className="flex items-start gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500 mt-0.5" />
              <div>
                <span className="font-medium">FR-6.4:</span>
                <span className="text-muted-foreground ml-2">
                  Save SKILL.md inside folder
                </span>
              </div>
            </div>
            
            <div className="flex items-start gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500 mt-0.5" />
              <div>
                <span className="font-medium">FR-6.4:</span>
                <span className="text-muted-foreground ml-2">
                  Copy reference screenshots if selected
                </span>
              </div>
            </div>
            
            <div className="flex items-start gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500 mt-0.5" />
              <div>
                <span className="font-medium">FR-6.4:</span>
                <span className="text-muted-foreground ml-2">
                  Validate file was saved successfully
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Export Dialog */}
      <ExportDialog
        open={isOpen}
        onOpenChange={setIsOpen}
        onExport={handleExport}
        defaultSkillName="create-user-account"
        isExporting={isExporting}
      />
    </div>
  );
}
