/**
 * SkillValidator Example
 * 
 * Demonstrates how to use the SkillValidator component
 * with a sample SKILL.md file.
 */

import { SkillValidator } from './SkillValidator';
import type { SemanticValidationResult } from '@/lib/semantic-judge';

/**
 * Sample SKILL.md content for testing
 */
const SAMPLE_SKILL = `---
name: login-to-github
description: Log in to GitHub using email and password
version: 1.0.0
author: Skill-E
created: 2024-01-28
metadata:
  category: authentication
  difficulty: beginner
  estimated_time: 2 minutes
---

# Login to GitHub

This skill demonstrates how to log in to GitHub using email and password.

## Parameters

| Parameter | Type | Required | Description | Example |
|-----------|------|----------|-------------|---------|
| \`{email}\` | string | Yes | GitHub account email | user@example.com |
| \`{password}\` | string | Yes | GitHub account password | ••••••••• |

## Prerequisites

- Valid GitHub account
- Internet connection
- Web browser installed

## Instructions

### Step 1: Navigate to GitHub

1. Open your web browser
2. Navigate to https://github.com/login
3. Wait for the page to load

### Step 2: Enter Credentials

1. Click on the email input field #login_field
2. Type {email} into the email field
3. Click on the password input field #password
4. Type {password} into the password field

### Step 3: Submit Login

1. PAUSE - Confirm you want to proceed with login
2. Click the "Sign in" button [type="submit"]
3. Wait for the page to redirect

### Step 4: Verify Login

1. Verify you see your profile icon in the top-right corner
2. Check that the URL contains "github.com" (not "github.com/login")

## Verification

- [ ] Successfully navigated to GitHub login page
- [ ] Email and password fields were filled correctly
- [ ] Login button was clicked
- [ ] Redirected to GitHub dashboard
- [ ] Profile icon is visible

## Troubleshooting

- **Issue**: Login page doesn't load
  - **Solution**: Check internet connection and try again
  
- **Issue**: Invalid credentials error
  - **Solution**: Verify email and password are correct

- **Issue**: Two-factor authentication required
  - **Solution**: This skill doesn't handle 2FA - complete manually

*Generated by Skill-E on 2024-01-28*
`;

/**
 * Sample semantic validation result (excellent score)
 */
const SAMPLE_VALIDATION_EXCELLENT: SemanticValidationResult = {
  score: 95,
  dimensions: {
    safety: 98,
    clarity: 94,
    completeness: 92,
  },
  strengths: [
    'Comprehensive PAUSE marker before login submission',
    'Clear parameter documentation with types and examples',
    'Excellent verification steps to confirm success',
    'Includes troubleshooting section for common issues',
    'Professional language and consistent formatting',
  ],
  weaknesses: [
    'Could add more details about 2FA handling',
  ],
  recommendations: [
    'Consider adding a separate skill for 2FA login',
    'Add estimated time for each step',
  ],
  isVerified: true,
};

/**
 * Sample semantic validation result (good score)
 */
const SAMPLE_VALIDATION_GOOD: SemanticValidationResult = {
  score: 82,
  dimensions: {
    safety: 85,
    clarity: 88,
    completeness: 75,
  },
  strengths: [
    'Clear step-by-step instructions',
    'Good parameter documentation',
    'Includes verification steps',
  ],
  weaknesses: [
    'Missing some edge case handling',
    'Limited error recovery guidance',
  ],
  recommendations: [
    'Add more troubleshooting scenarios',
    'Include rollback instructions',
  ],
  isVerified: false,
};

/**
 * Example component showing SkillValidator usage with excellent quality score
 */
export function SkillValidatorExample() {
  const handleComplete = (stats: any) => {
    console.log('Validation completed:', stats);
    alert(`Validation completed!\n\nSuccess: ${stats.completedSteps}/${stats.totalSteps}\nSuccess Rate: ${Math.round(stats.successRate * 100)}%`);
  };
  
  const handleCancel = () => {
    console.log('Validation cancelled');
    alert('Validation cancelled by user');
  };
  
  return (
    <div className="h-screen w-screen bg-background">
      <SkillValidator
        skillMarkdown={SAMPLE_SKILL}
        semanticValidation={SAMPLE_VALIDATION_EXCELLENT}
        config={{
          mode: 'hybrid',
          captureScreenshots: true,
          pauseOnError: true,
          pauseOnConfirmation: true,
          stepTimeout: 30000,
          continueOnFailure: false,
          maxRetries: 2,
        }}
        onComplete={handleComplete}
        onCancel={handleCancel}
      />
    </div>
  );
}

/**
 * Example showing good quality score (not verified)
 */
export function SkillValidatorGoodScoreExample() {
  return (
    <div className="h-screen w-screen bg-background">
      <SkillValidator
        skillMarkdown={SAMPLE_SKILL}
        semanticValidation={SAMPLE_VALIDATION_GOOD}
        onComplete={(stats) => console.log('Done:', stats)}
        onCancel={() => console.log('Cancelled')}
      />
    </div>
  );
}

/**
 * Example with custom skill content
 */
export function SkillValidatorCustomExample() {
  const customSkill = `---
name: simple-test
description: A simple test skill
---

# Simple Test Skill

## Instructions

### Step 1: First Action

1. Click the button #test-button
2. Wait for 2 seconds

### Step 2: Second Action

1. Type "Hello World" into the input field .text-input
2. PAUSE - Confirm the text is correct
3. Click submit

## Verification

- [ ] Button was clicked
- [ ] Text was entered
- [ ] Form was submitted
`;
  
  return (
    <div className="h-screen w-screen bg-background">
      <SkillValidator
        skillMarkdown={customSkill}
        onComplete={(stats) => console.log('Done:', stats)}
        onCancel={() => console.log('Cancelled')}
      />
    </div>
  );
}

/**
 * Example showing error handling
 */
export function SkillValidatorErrorExample() {
  const errorSkill = `---
name: error-test
description: Test error handling
---

# Error Test

## Instructions

### Step 1: This will fail

1. Click a non-existent element #does-not-exist
2. This should trigger an error

### Step 2: This should be skipped

1. This step won't run if step 1 fails
`;
  
  return (
    <div className="h-screen w-screen bg-background">
      <SkillValidator
        skillMarkdown={errorSkill}
        config={{
          pauseOnError: true,
          continueOnFailure: false,
        }}
        onComplete={(stats) => console.log('Completed with errors:', stats)}
        onCancel={() => console.log('Cancelled due to errors')}
      />
    </div>
  );
}

// Export default for easy testing
export default SkillValidatorExample;
