/**
 * Processing Mock - Versão simplificada para demonstração
 *
 * Gera SKILL.md de exemplo sem depender de Whisper/OCR
 * Usado para ter um fluxo funcional na entrega
 */

export interface MockProcessingResult {
  steps: Array<{
    id: string
    instruction: string
    timestamp: number
  }>
  variables: Array<{
    name: string
    value: string
    confidence: number
  }>
  transcription: string
}

export interface ProcessingProgress {
  stage: 'loading' | 'transcribing' | 'detecting' | 'generating' | 'complete' | 'error'
  percentage: number
  currentStep: string
  error?: string
}

/**
 * Process recording session (MOCK)
 * Simula processamento com delay para demonstração
 */
export async function processRecordingSessionMock(
  onProgress: (progress: ProcessingProgress) => void
): Promise<MockProcessingResult> {
  // Stage 1: Loading
  onProgress({
    stage: 'loading',
    percentage: 10,
    currentStep: 'Loading recording data...',
  })
  await delay(500)

  // Stage 2: Transcribing
  onProgress({
    stage: 'transcribing',
    percentage: 30,
    currentStep: 'Transcribing audio with Whisper...',
  })
  await delay(1000)

  // Stage 3: Detecting steps
  onProgress({
    stage: 'detecting',
    percentage: 60,
    currentStep: 'Detecting steps from transcription...',
  })
  await delay(800)

  // Stage 4: Generating
  onProgress({
    stage: 'generating',
    percentage: 90,
    currentStep: 'Generating SKILL.md...',
  })
  await delay(700)

  // Complete
  onProgress({
    stage: 'complete',
    percentage: 100,
    currentStep: 'Complete!',
  })

  // Return mock result
  return {
    steps: [
      { id: '1', instruction: 'Navigate to login page', timestamp: 1000 },
      { id: '2', instruction: 'Enter email in the email field', timestamp: 5000 },
      { id: '3', instruction: 'Enter password in the password field', timestamp: 8000 },
      { id: '4', instruction: 'Click the Sign In button', timestamp: 12000 },
    ],
    variables: [
      { name: 'email', value: 'user@example.com', confidence: 0.95 },
      { name: 'password', value: '********', confidence: 0.9 },
    ],
    transcription:
      'First, navigate to the login page. Then enter your email address. Next, type your password. Finally, click the sign in button.',
  }
}

/**
 * Generate SKILL.md from mock result
 */
export async function generateSkillMarkdown(result: MockProcessingResult): Promise<string> {
  const variablesSection =
    result.variables.length > 0
      ? result.variables.map(v => `| \`${v.name}\` | string | Yes | ${v.name} value |`).join('\n')
      : '| `example` | string | No | Example parameter |'

  const stepsSection = result.steps
    .map(
      (step, index) => `
### Step ${index + 1}
${step.instruction}
`
    )
    .join('\n')

  return `---
name: login-demo-skill
description: Automated login demonstration
version: 1.0.0
author: Skill-E
created: ${new Date().toISOString().split('T')[0]}
---

# Login Demo Skill

This skill demonstrates automated login functionality.

## Parameters

| Parameter | Type | Required | Description |
|-----------|------|----------|-------------|
${variablesSection}

## Instructions
${stepsSection}

## Verification

- [ ] Successfully navigated to login page
- [ ] Email entered correctly
- [ ] Password entered correctly
- [ ] Login button clicked
- [ ] Login successful

---
*Generated by Skill-E on ${new Date().toLocaleString()}*
`
}

function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms))
}
