/**
 * Skill Generator Tests
 * 
 * Tests for skill generation functionality
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { generateSkill } from './skill-generator';
import type { OptimizedContext } from './context-optimizer';

// Mock fetch globally
global.fetch = vi.fn();

describe('Skill Generator', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  const mockContext: OptimizedContext = {
    taskGoal: 'Create a new user account',
    keySteps: [
      {
        number: 1,
        description: 'Navigate to signup page',
        timeRange: { start: 0, end: 5000 },
        actions: { clicks: 1, textInputs: 0, annotations: 0 },
        notes: ['Clicked "Sign Up" button'],
        context: {
          window: 'Browser - Example App',
          application: 'Chrome',
        },
        ocrText: 'Welcome to Example App\nSign Up\nLog In',
      },
      {
        number: 2,
        description: 'Fill in user details',
        timeRange: { start: 5000, end: 15000 },
        actions: { clicks: 0, textInputs: 3, annotations: 1 },
        notes: ['Entered email', 'Entered password', 'Entered name'],
        context: {
          window: 'Sign Up - Example App',
          application: 'Chrome',
        },
        ocrText: 'Create Account\nEmail\nPassword\nFull Name',
      },
      {
        number: 3,
        description: 'Submit the form',
        timeRange: { start: 15000, end: 20000 },
        actions: { clicks: 1, textInputs: 0, annotations: 0 },
        notes: ['Clicked "Create Account" button'],
        context: {
          window: 'Sign Up - Example App',
          application: 'Chrome',
        },
      },
    ],
    fullNarration: 'First, I click on the Sign Up button. Then I enter my email address, password, and full name. Finally, I click Create Account to submit the form.',
    variables: [
      {
        name: 'email',
        type: 'email',
        description: 'User email address',
        exampleValue: 'user@example.com',
      },
      {
        name: 'password',
        type: 'password',
        description: 'User password',
        exampleValue: 'SecurePass123!',
      },
      {
        name: 'full_name',
        type: 'text',
        description: 'User full name',
        exampleValue: 'John Doe',
      },
    ],
    conditionals: [],
    summary: {
      totalSteps: 3,
      totalClicks: 2,
      totalTextInputs: 3,
      totalAnnotations: 1,
      durationSeconds: 20,
      mainApplication: 'Chrome',
    },
    references: {
      screenshotArchive: 'session-123',
      sessionDataPath: 'session-123',
    },
  };

  const mockAnthropicResponse = {
    content: [
      {
        text: `---
name: create-user-account
description: Create a new user account by filling in email, password, and full name.
compatibility: Web browser
license: Apache-2.0
metadata:
  author: Skill-E
  version: "1.0"
  recorded: "2024-01-26"
  source: demonstration
---

# Create User Account

Create a new user account in the application.

## Parameters

| Parameter | Type | Required | Description |
|-----------|------|----------|-------------|
| \`{email}\` | email | yes | User email address |
| \`{password}\` | password | yes | User password |
| \`{full_name}\` | text | yes | User full name |

## When to Use

- When you need to create a new user account
- When onboarding a new user

## Prerequisites

- Web browser open
- Access to the application signup page

## Instructions

### Step 1: Navigate to Signup Page

1. Click the "Sign Up" button

> **Note**: This is usually in the top right corner of the page

### Step 2: Fill in User Details

1. Enter \`{email}\` in the Email field
2. Enter \`{password}\` in the Password field
3. Enter \`{full_name}\` in the Full Name field

### Step 3: Submit the Form

1. Click the "Create Account" button
2. Wait for confirmation

## Verification

- [ ] User is redirected to dashboard or confirmation page
- [ ] Success message is displayed
- [ ] User can log in with the new credentials

## Troubleshooting

| Problem | Solution |
|---------|----------|
| Email already exists | Use a different email address |
| Password too weak | Use a stronger password with numbers and symbols |

---
*Generated by Skill-E from demonstration recording*`,
      },
    ],
  };

  describe('generateSkill', () => {
    it('should generate a valid SKILL.md with Anthropic', async () => {
      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        json: async () => mockAnthropicResponse,
      });

      const result = await generateSkill(mockContext, {
        provider: 'anthropic',
        model: 'claude-3-5-sonnet-20241022',
        apiKey: 'test-api-key',
      });

      expect(result.markdown).toBeTruthy();
      expect(result.frontmatter.name).toBe('create-user-account');
      expect(result.frontmatter.description).toContain('Create a new user account');
      expect(result.tokenCount).toBeGreaterThan(0);
      expect(result.metadata.provider).toBe('anthropic');
    });

    it('should generate tool definition with correct schema', async () => {
      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        json: async () => mockAnthropicResponse,
      });

      const result = await generateSkill(mockContext, {
        provider: 'anthropic',
        apiKey: 'test-api-key',
      });

      expect(result.toolDefinition.name).toBe('create_user_account');
      expect(result.toolDefinition.description).toContain('Create a new user account');
      expect(result.toolDefinition.input_schema.type).toBe('object');
      expect(result.toolDefinition.input_schema.properties).toHaveProperty('email');
      expect(result.toolDefinition.input_schema.properties).toHaveProperty('password');
      expect(result.toolDefinition.input_schema.properties).toHaveProperty('full_name');
      expect(result.toolDefinition.input_schema.required).toContain('email');
      expect(result.toolDefinition.input_schema.required).toContain('password');
      expect(result.toolDefinition.input_schema.required).toContain('full_name');
    });

    it('should throw error if API key is missing', async () => {
      await expect(
        generateSkill(mockContext, {
          provider: 'anthropic',
        })
      ).rejects.toThrow('API key is required');
    });

    it('should throw error if API call fails', async () => {
      (global.fetch as any).mockResolvedValueOnce({
        ok: false,
        status: 401,
        text: async () => 'Unauthorized',
      });

      await expect(
        generateSkill(mockContext, {
          provider: 'anthropic',
          apiKey: 'invalid-key',
        })
      ).rejects.toThrow('Anthropic API error');
    });

    it('should handle OpenAI provider', async () => {
      const mockOpenAIResponse = {
        choices: [
          {
            message: {
              content: mockAnthropicResponse.content[0].text,
            },
          },
        ],
      };

      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        json: async () => mockOpenAIResponse,
      });

      const result = await generateSkill(mockContext, {
        provider: 'openai',
        model: 'gpt-4',
        apiKey: 'test-api-key',
      });

      expect(result.markdown).toBeTruthy();
      expect(result.metadata.provider).toBe('openai');
    });

    it('should handle OpenRouter provider', async () => {
      const mockOpenRouterResponse = {
        choices: [
          {
            message: {
              content: mockAnthropicResponse.content[0].text,
            },
          },
        ],
      };

      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        json: async () => mockOpenRouterResponse,
      });

      const result = await generateSkill(mockContext, {
        provider: 'openrouter',
        model: 'anthropic/claude-3-5-sonnet',
        apiKey: 'test-api-key',
      });

      expect(result.markdown).toBeTruthy();
      expect(result.metadata.provider).toBe('openrouter');
    });

    it('should estimate token count correctly', async () => {
      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        json: async () => mockAnthropicResponse,
      });

      const result = await generateSkill(mockContext, {
        provider: 'anthropic',
        apiKey: 'test-api-key',
      });

      // Token count should be roughly markdown length / 4
      const expectedTokens = Math.ceil(result.markdown.length / 4);
      expect(result.tokenCount).toBe(expectedTokens);
    });

    it('should include generation metadata', async () => {
      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        json: async () => mockAnthropicResponse,
      });

      const result = await generateSkill(mockContext, {
        provider: 'anthropic',
        model: 'claude-3-5-sonnet-20241022',
        apiKey: 'test-api-key',
      });

      expect(result.metadata.generatedAt).toBeGreaterThan(0);
      expect(result.metadata.provider).toBe('anthropic');
      expect(result.metadata.model).toBe('claude-3-5-sonnet-20241022');
      expect(result.metadata.generationTimeMs).toBeGreaterThanOrEqual(0);
    });

    it('should handle context with conditionals', async () => {
      const contextWithConditionals: OptimizedContext = {
        ...mockContext,
        conditionals: [
          {
            condition: 'User already has an account',
            thenAction: 'Click "Log In" instead',
            elseAction: 'Continue with signup',
          },
        ],
      };

      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        json: async () => mockAnthropicResponse,
      });

      const result = await generateSkill(contextWithConditionals, {
        provider: 'anthropic',
        apiKey: 'test-api-key',
      });

      expect(result.markdown).toBeTruthy();
    });

    it('should handle context without variables', async () => {
      const contextWithoutVariables: OptimizedContext = {
        ...mockContext,
        variables: [],
      };

      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          content: [
            {
              text: `---
name: simple-task
description: A simple task without parameters.
---

# Simple Task

No parameters needed.

## Instructions

1. Do something

## Verification

- [ ] Task completed
`,
            },
          ],
        }),
      });

      const result = await generateSkill(contextWithoutVariables, {
        provider: 'anthropic',
        apiKey: 'test-api-key',
      });

      expect(result.markdown).toBeTruthy();
      expect(result.toolDefinition.input_schema.properties).toEqual({});
      expect(result.toolDefinition.input_schema.required).toEqual([]);
    });
  });

  describe('streaming', () => {
    it('should handle streaming responses', async () => {
      // Create a complete valid SKILL.md in chunks
      const fullContent = mockAnthropicResponse.content[0].text;
      const chunkSize = 100;
      const chunks: string[] = [];
      
      for (let i = 0; i < fullContent.length; i += chunkSize) {
        const chunk = fullContent.slice(i, i + chunkSize);
        chunks.push(`data: {"type":"content_block_delta","delta":{"text":${JSON.stringify(chunk)}}}\n`);
      }
      chunks.push('data: [DONE]\n');

      const mockReads = chunks.map(chunk => ({
        done: false,
        value: new TextEncoder().encode(chunk),
      }));
      mockReads.push({ done: true, value: undefined });

      const mockReader = {
        read: vi.fn(),
        releaseLock: vi.fn(),
      };

      // Set up the mock to return each chunk in sequence
      mockReads.forEach((read, index) => {
        mockReader.read.mockResolvedValueOnce(read);
      });

      (global.fetch as any).mockResolvedValueOnce({
        ok: true,
        body: {
          getReader: () => mockReader,
        },
      });

      const onChunk = vi.fn();

      const result = await generateSkill(mockContext, {
        provider: 'anthropic',
        apiKey: 'test-api-key',
        stream: true,
        onChunk,
      });

      // Verify that chunks were processed
      expect(onChunk).toHaveBeenCalled();
      expect(onChunk.mock.calls.length).toBeGreaterThan(0);
      
      // Verify the result is valid
      expect(result.markdown).toBeTruthy();
      expect(result.frontmatter.name).toBe('create-user-account');
    });
  });
});
