/**
 * Skill Parser Tests
 * 
 * Tests for SKILL.md parsing functionality
 */

import { describe, it, expect } from 'vitest';
import {
  parseSkill,
  getStepById,
  getStepsByStatus,
  getNextPendingStep,
  updateStepStatus,
  addStepFeedback,
  type SkillStep,
  type ParsedSkill,
} from './skill-parser';

describe('Skill Parser', () => {
  const sampleSkillMarkdown = `---
name: create-user-account
description: Create a new user account by filling in email, password, and full name.
compatibility: Web browser
license: Apache-2.0
metadata:
  author: Skill-E
  version: "1.0"
  recorded: "2024-01-26"
  source: demonstration
---

# Create User Account

Create a new user account in the application.

## Parameters

| Parameter | Type | Required | Description | Example |
|-----------|------|----------|-------------|---------|
| \`{email}\` | email | yes | User email address | user@example.com |
| \`{password}\` | password | yes | User password | SecurePass123! |
| \`{full_name}\` | text | yes | User full name | John Doe |

## When to Use

- When you need to create a new user account
- When onboarding a new user

## Prerequisites

- Web browser open
- Access to the application signup page
- Valid email address

## Instructions

### Step 1: Navigate to Signup Page

1. Click the "Sign Up" button
2. Wait for the page to load

> **Note**: This is usually in the top right corner of the page

### Step 2: Fill in User Details

1. Enter \`{email}\` in the Email field
2. Enter \`{password}\` in the Password field
3. Enter \`{full_name}\` in the Full Name field

### Step 3: Submit the Form

1. Click the "Create Account" button
2. PAUSE - Wait for user confirmation before proceeding
3. Verify success message is displayed

## Verification

- [ ] User is redirected to dashboard or confirmation page
- [ ] Success message is displayed
- [ ] User can log in with the new credentials

## Troubleshooting

| Problem | Solution |
|---------|----------|
| Email already exists | Use a different email address |
| Password too weak | Use a stronger password with numbers and symbols |

---
*Generated by Skill-E from demonstration recording*`;

  describe('parseSkill', () => {
    it('should parse frontmatter correctly', () => {
      const parsed = parseSkill(sampleSkillMarkdown);
      
      expect(parsed.name).toBe('create-user-account');
      expect(parsed.description).toBe('Create a new user account by filling in email, password, and full name.');
      expect(parsed.frontmatter.compatibility).toBe('Web browser');
      expect(parsed.frontmatter.license).toBe('Apache-2.0');
      expect(parsed.frontmatter.metadata).toBeDefined();
      expect(parsed.frontmatter.metadata.author).toBe('Skill-E');
      expect(parsed.frontmatter.metadata.version).toBe('1.0');
    });

    it('should extract parameters from table', () => {
      const parsed = parseSkill(sampleSkillMarkdown);
      
      expect(parsed.parameters).toHaveLength(3);
      
      expect(parsed.parameters[0]).toEqual({
        name: 'email',
        type: 'email',
        required: true,
        description: 'User email address',
        example: 'user@example.com',
      });
      
      expect(parsed.parameters[1]).toEqual({
        name: 'password',
        type: 'password',
        required: true,
        description: 'User password',
        example: 'SecurePass123!',
      });
      
      expect(parsed.parameters[2]).toEqual({
        name: 'full_name',
        type: 'text',
        required: true,
        description: 'User full name',
        example: 'John Doe',
      });
    });

    it('should extract prerequisites', () => {
      const parsed = parseSkill(sampleSkillMarkdown);
      
      expect(parsed.prerequisites).toHaveLength(3);
      expect(parsed.prerequisites).toContain('Web browser open');
      expect(parsed.prerequisites).toContain('Access to the application signup page');
      expect(parsed.prerequisites).toContain('Valid email address');
    });

    it('should extract verification items', () => {
      const parsed = parseSkill(sampleSkillMarkdown);
      
      expect(parsed.verificationItems).toHaveLength(3);
      expect(parsed.verificationItems).toContain('User is redirected to dashboard or confirmation page');
      expect(parsed.verificationItems).toContain('Success message is displayed');
      expect(parsed.verificationItems).toContain('User can log in with the new credentials');
    });

    it('should extract steps from instructions', () => {
      const parsed = parseSkill(sampleSkillMarkdown);
      
      expect(parsed.steps.length).toBeGreaterThan(0);
      
      // Check first step
      const firstStep = parsed.steps[0];
      expect(firstStep.stepNumber).toBe(1);
      expect(firstStep.section).toBe('Navigate to Signup Page');
      expect(firstStep.instruction).toContain('Click');
      expect(firstStep.instruction).toContain('Sign Up');
    });

    it('should handle skill without frontmatter', () => {
      const minimalSkill = `# Simple Skill

## Instructions

### Step 1: Do Something

1. Click the button`;

      const parsed = parseSkill(minimalSkill);
      
      expect(parsed.name).toBe('unnamed-skill');
      expect(parsed.description).toBe('');
      expect(parsed.steps.length).toBeGreaterThan(0);
    });

    it('should handle skill without parameters', () => {
      const noParamsSkill = `---
name: simple-skill
description: A simple skill
---

## Instructions

### Step 1: Do Something

1. Click the button`;

      const parsed = parseSkill(noParamsSkill);
      
      expect(parsed.parameters).toHaveLength(0);
    });
  });

  describe('Action Type Detection', () => {
    it('should detect click actions', () => {
      const clickSkill = `## Instructions

### Step 1: Click Button

1. Click the "Submit" button
2. Press the Enter key
3. Tap the icon`;

      const parsed = parseSkill(clickSkill);
      
      expect(parsed.steps[0].actionType).toBe('click');
      expect(parsed.steps[1].actionType).toBe('click');
      expect(parsed.steps[2].actionType).toBe('click');
    });

    it('should detect type actions', () => {
      const typeSkill = `## Instructions

### Step 1: Enter Data

1. Type "hello" in the field
2. Enter your email address
3. Fill in the form`;

      const parsed = parseSkill(typeSkill);
      
      expect(parsed.steps[0].actionType).toBe('type');
      expect(parsed.steps[1].actionType).toBe('type');
      expect(parsed.steps[2].actionType).toBe('type');
    });

    it('should detect navigate actions', () => {
      const navSkill = `## Instructions

### Step 1: Go to Page

1. Navigate to the homepage
2. Open the settings page
3. Visit the dashboard`;

      const parsed = parseSkill(navSkill);
      
      expect(parsed.steps[0].actionType).toBe('navigate');
      expect(parsed.steps[1].actionType).toBe('navigate');
      expect(parsed.steps[2].actionType).toBe('navigate');
    });

    it('should detect wait actions', () => {
      const waitSkill = `## Instructions

### Step 1: Wait

1. Wait for the page to load
2. Pause for 2 seconds
3. Delay until element appears`;

      const parsed = parseSkill(waitSkill);
      
      expect(parsed.steps[0].actionType).toBe('wait');
      expect(parsed.steps[1].actionType).toBe('wait');
      expect(parsed.steps[2].actionType).toBe('wait');
    });

    it('should detect verify actions', () => {
      const verifySkill = `## Instructions

### Step 1: Check Results

1. Verify the message is displayed
2. Check that the form is valid
3. Ensure the data is saved`;

      const parsed = parseSkill(verifySkill);
      
      expect(parsed.steps[0].actionType).toBe('verify');
      expect(parsed.steps[1].actionType).toBe('verify');
      expect(parsed.steps[2].actionType).toBe('verify');
    });

    it('should detect confirmation points', () => {
      const confirmSkill = `## Instructions

### Step 1: Confirm Action

1. Click the delete button
2. PAUSE - Wait for user confirmation
3. CONFIRM before proceeding`;

      const parsed = parseSkill(confirmSkill);
      
      expect(parsed.steps[1].actionType).toBe('confirm');
      expect(parsed.steps[1].requiresConfirmation).toBe(true);
      expect(parsed.steps[2].actionType).toBe('confirm');
      expect(parsed.steps[2].requiresConfirmation).toBe(true);
    });

    it('should detect more action keywords', () => {
      const skill = `## Instructions

### Step 1: Various Actions

1. Hit the checkbox
2. Activate the feature
3. Paste the text
4. Insert the value
5. Sleep for 1 second
6. Assert the value is correct`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].actionType).toBe('click');
      expect(parsed.steps[1].actionType).toBe('click');
      expect(parsed.steps[2].actionType).toBe('type');
      expect(parsed.steps[3].actionType).toBe('type');
      expect(parsed.steps[4].actionType).toBe('wait');
      expect(parsed.steps[5].actionType).toBe('verify');
    });

    it('should prioritize navigate over click for links', () => {
      const skill = `## Instructions

### Step 1: Navigate

1. Navigate to the homepage
2. Click link to go to settings page`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].actionType).toBe('navigate');
      // Second step has both "click" and "page", should be navigate
      expect(parsed.steps[1].actionType).toBe('navigate');
    });

    it('should detect click when navigate context is missing', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click the button to open dialog`;

      const parsed = parseSkill(skill);
      
      // Has "open" but no page/url context, should be click
      expect(parsed.steps[0].actionType).toBe('click');
    });

    it('should handle ambiguous instructions', () => {
      const skill = `## Instructions

### Step 1: Do Something

1. Perform the action`;

      const parsed = parseSkill(skill);
      
      // No clear action keyword, should be unknown
      expect(parsed.steps[0].actionType).toBe('unknown');
    });
  });

  describe('Target Extraction', () => {
    it('should extract quoted text as description', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click the "Sign Up" button
2. Press 'Submit'`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.description).toBe('Sign Up');
      expect(parsed.steps[1].target?.description).toBe('Submit');
    });

    it('should extract CSS ID selectors', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click #submit-button
2. Click on #login-form`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.selector).toBe('#submit-button');
      expect(parsed.steps[1].target?.selector).toBe('#login-form');
    });

    it('should extract CSS class selectors', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click .primary-btn
2. Select .dropdown-item`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.selector).toBe('.primary-btn');
      expect(parsed.steps[1].target?.selector).toBe('.dropdown-item');
    });

    it('should extract CSS attribute selectors', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click [data-testid="login"]
2. Select [type=submit]`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.selector).toBe('[data-testid="login"]');
      expect(parsed.steps[1].target?.selector).toBe('[type=submit]');
    });

    it('should extract data attributes', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click element with data-action="submit"
2. Select data-testid="user-menu"`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.selector).toBe('[data-action="submit"]');
      expect(parsed.steps[1].target?.selector).toBe('[data-testid="user-menu"]');
    });

    it('should extract ARIA attributes', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click element with aria-label="Close"
2. Select aria-role="button"`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.selector).toBe('[aria-label="Close"]');
      expect(parsed.steps[1].target?.selector).toBe('[aria-role="button"]');
    });

    it('should extract XPath selectors', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click //button[@id='submit']
2. Select //div[@class='container']/button`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.selector).toBe("//button[@id='submit']");
      expect(parsed.steps[1].target?.selector).toBe("//div[@class='container']/button");
    });

    it('should prioritize ID over class selectors', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click #submit-button .primary-btn`;

      const parsed = parseSkill(skill);
      
      // Should extract ID first
      expect(parsed.steps[0].target?.selector).toBe('#submit-button');
    });

    it('should extract variables as text', () => {
      const skill = `## Instructions

### Step 1: Type

1. Enter {email} in the field
2. Type {password} and {username}`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.text).toBe('{email}');
      expect(parsed.steps[1].target?.text).toBe('{password} {username}');
    });

    it('should extract named coordinates', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click at (x: 100, y: 200)
2. Click at (x:150, y:250)`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.coordinates).toEqual({ x: 100, y: 200 });
      expect(parsed.steps[1].target?.coordinates).toEqual({ x: 150, y: 250 });
    });

    it('should extract bracket coordinates', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click at [100, 200]
2. Click at [150, 250]`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.coordinates).toEqual({ x: 100, y: 200 });
      expect(parsed.steps[1].target?.coordinates).toEqual({ x: 150, y: 250 });
    });

    it('should extract parenthesis coordinates', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click at (100, 200)
2. Click at (150, 250)`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.coordinates).toEqual({ x: 100, y: 200 });
      expect(parsed.steps[1].target?.coordinates).toEqual({ x: 150, y: 250 });
    });

    it('should validate coordinate ranges', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click at (99999, 99999)`;

      const parsed = parseSkill(skill);
      
      // Should not extract unreasonably large coordinates
      expect(parsed.steps[0].target?.coordinates).toBeUndefined();
    });

    it('should extract image references', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click on screenshot-1.png
2. Click on reference-image.jpg`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target?.imageRef).toBe('screenshot-1.png');
      expect(parsed.steps[1].target?.imageRef).toBe('reference-image.jpg');
    });

    it('should extract element type descriptions', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click the Submit button
2. Select the Email input field`;

      const parsed = parseSkill(skill);
      
      // Should extract element type when no quoted text
      expect(parsed.steps[0].target?.description).toBeDefined();
      expect(parsed.steps[1].target?.description).toBeDefined();
    });

    it('should handle multiple target types in one instruction', () => {
      const skill = `## Instructions

### Step 1: Click

1. Click "Submit" button at #submit-btn or (x: 100, y: 200)`;

      const parsed = parseSkill(skill);
      
      // Should extract all available target info
      expect(parsed.steps[0].target?.description).toBe('Submit');
      expect(parsed.steps[0].target?.selector).toBe('#submit-btn');
      expect(parsed.steps[0].target?.coordinates).toEqual({ x: 100, y: 200 });
    });

    it('should handle steps with no target', () => {
      const skill = `## Instructions

### Step 1: Wait

1. Wait for page to load`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps[0].target).toBeUndefined();
    });
  });

  describe('Step Management Functions', () => {
    const mockSteps: SkillStep[] = [
      {
        id: 'step-1-1',
        index: 0,
        instruction: 'Click button',
        actionType: 'click',
        requiresConfirmation: false,
        status: 'pending',
      },
      {
        id: 'step-1-2',
        index: 1,
        instruction: 'Type text',
        actionType: 'type',
        requiresConfirmation: false,
        status: 'success',
      },
      {
        id: 'step-2-1',
        index: 2,
        instruction: 'Verify result',
        actionType: 'verify',
        requiresConfirmation: false,
        status: 'failed',
        error: 'Element not found',
      },
    ];

    describe('getStepById', () => {
      it('should find step by id', () => {
        const step = getStepById(mockSteps, 'step-1-2');
        
        expect(step).toBeDefined();
        expect(step?.instruction).toBe('Type text');
      });

      it('should return undefined for non-existent id', () => {
        const step = getStepById(mockSteps, 'step-999');
        
        expect(step).toBeUndefined();
      });
    });

    describe('getStepsByStatus', () => {
      it('should filter steps by status', () => {
        const pendingSteps = getStepsByStatus(mockSteps, 'pending');
        
        expect(pendingSteps).toHaveLength(1);
        expect(pendingSteps[0].id).toBe('step-1-1');
      });

      it('should return empty array if no steps match', () => {
        const skippedSteps = getStepsByStatus(mockSteps, 'skipped');
        
        expect(skippedSteps).toHaveLength(0);
      });
    });

    describe('getNextPendingStep', () => {
      it('should return first pending step', () => {
        const nextStep = getNextPendingStep(mockSteps);
        
        expect(nextStep).toBeDefined();
        expect(nextStep?.id).toBe('step-1-1');
      });

      it('should return undefined if no pending steps', () => {
        const completedSteps = mockSteps.map(s => ({ ...s, status: 'success' as const }));
        const nextStep = getNextPendingStep(completedSteps);
        
        expect(nextStep).toBeUndefined();
      });
    });

    describe('updateStepStatus', () => {
      it('should update step status', () => {
        const updated = updateStepStatus(mockSteps, 'step-1-1', 'running');
        
        const step = getStepById(updated, 'step-1-1');
        expect(step?.status).toBe('running');
      });

      it('should add error message', () => {
        const updated = updateStepStatus(mockSteps, 'step-1-1', 'failed', 'Test error');
        
        const step = getStepById(updated, 'step-1-1');
        expect(step?.status).toBe('failed');
        expect(step?.error).toBe('Test error');
      });

      it('should not modify other steps', () => {
        const updated = updateStepStatus(mockSteps, 'step-1-1', 'success');
        
        expect(updated[1].status).toBe('success'); // Unchanged
        expect(updated[2].status).toBe('failed'); // Unchanged
      });
    });

    describe('addStepFeedback', () => {
      it('should add feedback to step', () => {
        const updated = addStepFeedback(mockSteps, 'step-2-1', 'Element selector was wrong');
        
        const step = getStepById(updated, 'step-2-1');
        expect(step?.feedback).toBe('Element selector was wrong');
      });

      it('should not modify other steps', () => {
        const updated = addStepFeedback(mockSteps, 'step-2-1', 'Test feedback');
        
        expect(updated[0].feedback).toBeUndefined();
        expect(updated[1].feedback).toBeUndefined();
      });
    });
  });

  describe('Edge Cases', () => {
    it('should handle empty markdown', () => {
      const parsed = parseSkill('');
      
      expect(parsed.name).toBe('unnamed-skill');
      expect(parsed.steps).toHaveLength(0);
      expect(parsed.parameters).toHaveLength(0);
    });

    it('should handle markdown with only frontmatter', () => {
      const skill = `---
name: test-skill
description: Test
---`;

      const parsed = parseSkill(skill);
      
      expect(parsed.name).toBe('test-skill');
      expect(parsed.steps).toHaveLength(0);
    });

    it('should handle steps without numbered lists', () => {
      const skill = `## Instructions

### Step 1: Do Something

Just do it.`;

      const parsed = parseSkill(skill);
      
      expect(parsed.steps).toHaveLength(0);
    });

    it('should handle malformed parameters table', () => {
      const skill = `## Parameters

| Parameter | Type |
|-----------|------|
| email | text |

## Instructions

### Step 1: Test

1. Do something`;

      const parsed = parseSkill(skill);
      
      // Should not crash, but may not parse parameters correctly
      expect(parsed).toBeDefined();
    });

    it('should handle multiple action types in one instruction', () => {
      const skill = `## Instructions

### Step 1: Complex Action

1. Click the button and wait for the page to load`;

      const parsed = parseSkill(skill);
      
      // Should detect the first action type (click)
      // Note: "wait for page to load" contains "load" which might trigger navigate
      // But "click" comes first, so it should be detected as click
      expect(parsed.steps[0].actionType).toBe('click');
    });
  });
});
