/**
 * Skill Preview Test Component
 * 
 * Tests the SkillPreview component with sample data.
 * 
 * Requirements: FR-6.2, FR-6.6
 */

import * as React from 'react';
import { SkillPreview } from './SkillPreview';
import type { GeneratedSkill } from '@/lib/skill-generator';

/**
 * Sample generated skill for testing
 */
const SAMPLE_SKILL: GeneratedSkill = {
  markdown: `---
name: create-user-account
description: Create a new user account in the admin dashboard with email verification.
compatibility: Web application, requires admin access
license: Apache-2.0
metadata:
  author: Skill-E
  version: "1.0"
  recorded: "2024-01-27"
  source: demonstration
---

# Create User Account

This skill demonstrates how to create a new user account in the admin dashboard with proper email verification and role assignment.

## Parameters

| Parameter | Type | Required | Description |
|-----------|------|----------|-------------|
| \`{email}\` | email | yes | User's email address |
| \`{full_name}\` | text | yes | User's full name |
| \`{role}\` | selection | yes | Options: \`admin\` \\| \`editor\` \\| \`viewer\` |

## When to Use

- When you need to add a new user to the system
- When onboarding team members
- When granting access to external collaborators

## Prerequisites

- Admin access to the dashboard
- Valid email domain for the organization
- User role permissions configured

## Instructions

### Step 1: Navigate to Users

1. Click on the "Users" menu item in the left sidebar
2. Wait for the users list to load

> **Note**: The users page may take a few seconds to load if there are many users

### Step 2: Open Create User Form

1. Click the "Add User" button in the top-right corner
2. The create user modal will appear

### Step 3: Fill User Details

1. Enter the email address in the "Email" field: \`{email}\`
2. Enter the full name in the "Full Name" field: \`{full_name}\`
3. Select the role from the dropdown: \`{role}\`

**If \`{role}\` = \`admin\`:**
1. Check the "Grant full access" checkbox
2. Review the permissions list

**If \`{role}\` = \`editor\` or \`viewer\`:**
1. Leave "Grant full access" unchecked
2. Select specific permissions as needed

### Step 4: Submit and Verify

1. Click the "Create User" button
2. Wait for the success message
3. Verify the user appears in the users list

## Verification

- [ ] User appears in the users list
- [ ] Email verification sent successfully
- [ ] Correct role assigned
- [ ] User can log in with temporary password

## Troubleshooting

| Problem | Solution |
|---------|----------|
| Email already exists | Check if user is already in the system |
| Invalid email domain | Verify the email domain is whitelisted |
| Permission denied | Ensure you have admin access |

---
*Generated by Skill-E from demonstration recording*
`,
  frontmatter: {
    name: 'create-user-account',
    description: 'Create a new user account in the admin dashboard with email verification.',
    compatibility: 'Web application, requires admin access',
    license: 'Apache-2.0',
    metadata: {
      author: 'Skill-E',
      version: '1.0',
      recorded: '2024-01-27',
      source: 'demonstration',
    },
  },
  toolDefinition: {
    name: 'create_user_account',
    description: 'Create a new user account in the admin dashboard with email verification.',
    input_schema: {
      type: 'object',
      properties: {
        email: {
          type: 'string',
          description: "User's email address",
        },
        full_name: {
          type: 'string',
          description: "User's full name",
        },
        role: {
          type: 'string',
          description: 'Options: `admin` | `editor` | `viewer`',
          enum: ['admin', 'editor', 'viewer'],
        },
      },
      required: ['email', 'full_name', 'role'],
    },
  },
  tokenCount: 1247,
  metadata: {
    generatedAt: Date.now(),
    provider: 'anthropic',
    model: 'claude-3-5-sonnet-20241022',
    generationTimeMs: 3542,
  },
};

/**
 * SkillPreviewTest Component
 * 
 * Displays the SkillPreview component with sample data for testing.
 */
export function SkillPreviewTest() {
  const [regenerateCount, setRegenerateCount] = React.useState(0);

  const handleRegenerate = React.useCallback(() => {
    setRegenerateCount(prev => prev + 1);
    console.log('Regenerate requested');
  }, []);

  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-5xl mx-auto space-y-8">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold text-foreground">
            Skill Preview Test
          </h1>
          <p className="text-muted-foreground">
            Testing the SkillPreview component with sample generated skill data.
          </p>
          {regenerateCount > 0 && (
            <p className="text-sm text-primary">
              Regenerate clicked {regenerateCount} time(s)
            </p>
          )}
        </div>

        <SkillPreview
          skill={SAMPLE_SKILL}
          onRegenerate={handleRegenerate}
        />

        {/* Test with high token count */}
        <div className="pt-8 border-t">
          <h2 className="text-2xl font-bold text-foreground mb-4">
            High Token Count Test
          </h2>
          <SkillPreview
            skill={{
              ...SAMPLE_SKILL,
              tokenCount: 5500, // Over the limit
            }}
          />
        </div>

        {/* Test with minimal frontmatter */}
        <div className="pt-8 border-t">
          <h2 className="text-2xl font-bold text-foreground mb-4">
            Minimal Frontmatter Test
          </h2>
          <SkillPreview
            skill={{
              ...SAMPLE_SKILL,
              frontmatter: {
                name: 'simple-skill',
                description: 'A simple skill with minimal metadata.',
              },
            }}
          />
        </div>
      </div>
    </div>
  );
}
