/**
 * Skill Editor Test Component
 * 
 * Interactive test for the SkillEditor component.
 * Tests editing, preview, undo/redo, and save functionality.
 */

import * as React from 'react';
import { SkillEditor } from './SkillEditor/SkillEditor';
import { Button } from './ui/button';
import { Separator } from './ui/separator';
import type { GeneratedSkill } from '@/lib/skill-generator';

/**
 * Sample skill for testing
 */
const SAMPLE_SKILL: GeneratedSkill = {
  markdown: `---
name: create-user-account
description: Create a new user account in the admin dashboard with email verification.
compatibility: Web application, requires admin access
license: Apache-2.0
metadata:
  author: Skill-E
  version: "1.0"
  recorded: "2024-01-26"
  source: demonstration
---

# Create User Account

This skill demonstrates how to create a new user account in the admin dashboard with proper email verification and role assignment.

## Parameters

| Parameter | Type | Required | Description |
|-----------|------|----------|-------------|
| \`{email}\` | email | yes | User's email address |
| \`{full_name}\` | text | yes | User's full name |
| \`{role}\` | selection | yes | Options: \`admin\` \\| \`editor\` \\| \`viewer\` |

## When to Use

- When you need to add a new team member to the system
- When onboarding a new client or partner
- When setting up test accounts for development

## Prerequisites

- Admin access to the dashboard
- Valid email address for the new user
- Knowledge of appropriate role for the user

## Instructions

### Step 1: Navigate to Users Page

1. Click on the "Users" menu item in the left sidebar
2. Wait for the users list to load

> **Note**: The users page may take a few seconds to load if there are many users

### Step 2: Open Create User Form

1. Click the "Add User" button in the top-right corner
2. The create user form will appear as a modal dialog

### Step 3: Fill in User Details

1. Enter the email address in the "Email" field: \`{email}\`
2. Enter the full name in the "Full Name" field: \`{full_name}\`
3. Select the appropriate role from the "Role" dropdown: \`{role}\`

**If \`{role}\` = \`admin\`:**
1. Check the "Grant full access" checkbox
2. Review the permissions list

**If \`{role}\` = \`editor\` or \`viewer\`:**
1. Leave the "Grant full access" checkbox unchecked
2. Select specific permissions as needed

### Step 4: Send Invitation

1. Click the "Send Invitation" button at the bottom of the form
2. Wait for the success message to appear

### Step 5: Verify Creation

1. Check that the new user appears in the users list
2. Verify the email address and role are correct
3. Confirm that an invitation email was sent

## Verification

- [ ] User appears in the users list
- [ ] Email address is correct
- [ ] Role is assigned correctly
- [ ] Invitation email was sent
- [ ] User can log in with the invitation link

## Troubleshooting

| Problem | Solution |
|---------|----------|
| Email already exists | Check if user already has an account, or use a different email |
| Invitation not sent | Check email service status, verify email address is valid |
| Permission denied | Ensure you have admin access to create users |
| Form validation error | Review all required fields and correct any errors |

---
*Generated by Skill-E from demonstration recording*
`,
  frontmatter: {
    name: 'create-user-account',
    description: 'Create a new user account in the admin dashboard with email verification.',
    compatibility: 'Web application, requires admin access',
    license: 'Apache-2.0',
    metadata: {
      author: 'Skill-E',
      version: '1.0',
      recorded: '2024-01-26',
      source: 'demonstration',
    },
  },
  toolDefinition: {
    name: 'create_user_account',
    description: 'Create a new user account in the admin dashboard with email verification.',
    input_schema: {
      type: 'object',
      properties: {
        email: {
          type: 'string',
          description: "User's email address",
        },
        full_name: {
          type: 'string',
          description: "User's full name",
        },
        role: {
          type: 'string',
          description: 'User role',
          enum: ['admin', 'editor', 'viewer'],
        },
      },
      required: ['email', 'full_name', 'role'],
    },
  },
  tokenCount: 1250,
  metadata: {
    generatedAt: Date.now(),
    provider: 'anthropic',
    model: 'claude-3-5-sonnet-20241022',
    generationTimeMs: 3500,
  },
};

/**
 * SkillEditorTest Component
 */
export function SkillEditorTest() {
  const [savedContent, setSavedContent] = React.useState<string | null>(null);
  const [readOnly, setReadOnly] = React.useState(false);
  const [regenerateCount, setRegenerateCount] = React.useState(0);

  const handleSave = React.useCallback((markdown: string) => {
    console.log('Save callback triggered');
    console.log('Content length:', markdown.length);
    console.log('First 100 chars:', markdown.substring(0, 100));
    setSavedContent(markdown);
    alert('Skill saved! Check console for details.');
  }, []);

  const handleRegenerate = React.useCallback(() => {
    console.log('Regenerate callback triggered');
    setRegenerateCount(prev => prev + 1);
    alert(`Regenerate requested (${regenerateCount + 1} times)`);
  }, [regenerateCount]);

  return (
    <div className="h-screen flex flex-col bg-background">
      {/* Test Controls */}
      <div className="p-4 border-b bg-card">
        <div className="max-w-7xl mx-auto">
          <h1 className="text-2xl font-bold mb-4">Skill Editor Test</h1>
          
          <div className="flex items-center gap-4 mb-4">
            <div className="flex items-center gap-2">
              <label className="text-sm font-medium">Read-only mode:</label>
              <input
                type="checkbox"
                checked={readOnly}
                onChange={(e) => setReadOnly(e.target.checked)}
                className="h-4 w-4"
              />
            </div>
            
            <Separator orientation="vertical" className="h-6" />
            
            <div className="text-sm text-muted-foreground">
              Regenerate count: {regenerateCount}
            </div>
            
            {savedContent && (
              <>
                <Separator orientation="vertical" className="h-6" />
                <div className="text-sm text-green-600 dark:text-green-500">
                  ✓ Content saved ({savedContent.length} chars)
                </div>
              </>
            )}
          </div>
          
          <div className="space-y-2">
            <h2 className="text-sm font-semibold">Test Instructions:</h2>
            <ul className="text-sm text-muted-foreground space-y-1 list-disc list-inside">
              <li>Try editing the markdown content in the editor</li>
              <li>Switch between Edit, Split, and Preview modes</li>
              <li>Test undo/redo with buttons or Ctrl/Cmd + Z</li>
              <li>Test save with button or Ctrl/Cmd + S</li>
              <li>Try the Reset button to revert changes</li>
              <li>Click Regenerate to test the callback</li>
              <li>Enable read-only mode to test disabled state</li>
              <li>Check token count warning by adding lots of text</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Editor */}
      <div className="flex-1 overflow-hidden">
        <div className="h-full max-w-7xl mx-auto">
          <SkillEditor
            skill={SAMPLE_SKILL}
            onSave={handleSave}
            onRegenerate={handleRegenerate}
            readOnly={readOnly}
          />
        </div>
      </div>
    </div>
  );
}
